project:
  type: website
  output-dir: docs

website:
  title: "Meshinchi and Locatelli Lab Documentation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: "Standards and Definitions"
        menu: 
          - text: "Installation on WSL"
            href: details/software_install_wsl.qmd
    right:
      - icon: github
        href: https://github.com/Meshinchi-Lab/contributing_guidelines
  sidebar:
    style: "docked"
    search: true
    contents:
      - prerequisites.qmd
      - git_github_overview.qmd
      - code_review.qmd

  page-navigation: true

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    link-external-newwindow: true
    link-external-icon: true

editor: source

