project:
  type: website
  output-dir: docs

website:
  title: "Meshinchi and Locatelli Lab Documentation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/Meshinchi-Lab/ospedale_bambino_gesu_docs
  sidebar:
    style: "docked"
    search: true
    contents:
      - prerequisites.qmd
      - git_github_overview.qmd
  page-navigation: true

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

